
for i=1:5
sma = NewStateMatrix(); %generate a new empty state matrix

sma = AddState(sma, 'Name', 'TrialStart', ...
    'Timer', 0, ...
    'StateChangeCondition', {'ObserverDeck1_1', 'CountingWindow'},...
    'OutputActions',{'ObserverDeck1',30});

sma = AddState(sma, 'Name', 'CountingWindow', ...
    'Timer', 10, ...
    'StateChangeCondition', {'Tup', 'StopCounting'},...
    'OutputActions',{});

sma = AddState(sma, 'Name', 'StopCounting', ...
    'Timer', 0, ...
    'StateChangeCondition', {'Tup', 'CheckBreak'},...
    'OutputActions',{'ObserverDeck1',31});

sma = AddState(sma, 'Name', 'CheckBreak', ...
    'Timer', 0, ...
    'StateChangeCondition', {'ObserverDeck1_3', 'Success', 'ObserverDeck1_4', 'Failure'},...
    'OutputActions',{'ObserverDeck1',32});

sma = AddState(sma, 'Name', 'Success', ...
    'Timer', 5, ...
    'StateChangeCondition', {'Tup', '>exit'},...
    'OutputActions',{'PWM1',255,'PWM2',255, 'PWM3',255});

sma = AddState(sma, 'Name', 'Failure', ...
    'Timer', 5, ...
    'StateChangeCondition', {'Tup', '>exit'},...
    'OutputActions',{'PWM1',255,'PWM2',255, 'PWM3',255});

 SendStateMatrix(sma); %Se
  RawEvents = RunStateMatrix; 
  
  end





